basic setup for solipool project
SoliPool/SoliPool pull request #1
Opened 2020-03-20 22:14 UTC by JohannaSchmidt

- used spring initializr to setup basic project
- added H2, rest and kotlin support

Change-Id: Ibb752d1cb6a000ac124459d08e27ff993c9d98d0

2020-03-20 22:38 UTC, d4l-w4r requested changes
Schaut mal ob es bei euch so läuft. 
Aber ohne die vorgeschlagenen Änderungen lief der gradle sync bei mir nicht durch

2020-03-20 22:38 UTC, danielw93 commented on build.gradle.kts
> +extra["snippetsDir"] = file("build/generated-snippets")
Ich musste hier 
```
val snippetsDir = file("build/generated-snippets")
extra["snippetsDir"] = snippetsDir
```
draus machen, weil ich sonst unten in Zeile 53 und 57 Fehler hatte

2020-03-20 22:38 UTC, danielw93 commented on build.gradle.kts
> +	dependsOn(test)
hier musste ich tasks.test draus machen damit es läuft

2020-03-21 07:27 UTC, fzuellich commented on build.gradle.kts
> +	dependsOn(test)
Auch mit dem Gradle-Wrapper? Würde mich total wundern, wenn das so auseinander läuft?

2020-03-21 08:50 UTC, danielw93 commented on build.gradle.kts
> +	dependsOn(test)
Also bei dir läuft es so?

2020-03-21 09:30 UTC, fzuellich commented on build.gradle.kts
> +		jvmTarget = "1.8"
Wir wollen 1.11! Auch wenn Kotlin unten drunter ein paar Sachen eh anders macht. :)

2020-03-21 09:33 UTC, merged